"""The registry and the community store, end to end.

The registry's claim is a lifecycle rather than a shape: a third party exports a
pack, publishes it under a tier, and a household can then browse the index,
install the pack by digest, and run it. This module drives that whole path -- on
a temporary registry (a fresh copy of the committed schema, tiers and empty
revocation list) and against a temporary installation root (a copy of the
committed catalog, schemas and packs) -- so the scenario the phase exists for is
exercised rather than described:

    export -> publish -> generate -> check -> browse -> install -> run

The packs are generated by `packfactory` rather than committed, because a pack a
third party publishes is exactly one the repository does not contain, and a
committed fixture would be a pack the store could have reached a second way.
Where a check's *failure* is the point -- a revoked pack, a widened grant, a
typosquat -- the violating input is built here for the same reason the other
suites build theirs.

Every check names the implementation that would falsify it. The recurring claim
is that the publishing side and the consuming side read one pointer tree and one
digest, and that a published manifest's `provides` paths are the repo-relative
form the sandbox installs -- so a change that made the two disagree would turn
one of these red.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
import yaml

from engine.install import digest as pack_digest
from engine.vocabulary import Vocabulary
from openhouse import packs
from openhouse.facade import open_session
from tools.catalog import paths
from tools.registry import layout
from tools.registry.checks import (
    Submission,
    check_permission_diff,
    check_revocation,
    check_schema,
    check_typosquat,
    run_checks,
)
from tools.registry.errors import RegistryError
from tools.registry.index import (
    Revocation,
    generate,
    load_index,
    load_revocations,
    pointer_files,
    verify_current,
)
from tools.registry.pointer import Pointer, load_pointer, pointer_schema, schema_errors
from tools.registry.publish import export_template, publish
from tools.registry.store import Store
from tools.registry.tiers import TIER_NAMES, TierError, load_tiers

from .packfactory import pack

if TYPE_CHECKING:
    from openhouse.facade import OpenHouse
    from sim.scenario import RunResult, Scenario

ROOT = paths.ROOT
COMMITTED = ROOT / layout.DIRECTORY
SCENARIOS = ROOT / "scenarios"

#: A commit that is the right shape for a pointer's `commit` field.
COMMIT = "a1b2c3d4" * 5


@pytest.fixture(scope="module")
def vocabulary() -> Vocabulary:
    """The committed catalog, loaded once for the module."""
    return Vocabulary.load(ROOT)


def _registry(tmp_path: Path) -> Path:
    """A writable registry: the committed policy files, and no pointers yet.

    The schema and the tier list are the committed ones, copied rather than
    restated, because the point of the temporary tree is to exercise publishing
    against the real rules -- a hand-written stand-in for the tiers would let a
    change to `registry/tiers.yaml` pass this suite untouched.
    """
    root = tmp_path / "registry"
    (root / layout.POINTERS_DIRECTORY).mkdir(parents=True)
    for name in (layout.POINTER_SCHEMA_FILENAME, layout.TIERS_FILENAME):
        shutil.copyfile(COMMITTED / name, root / name)
    (root / layout.REVOCATIONS_FILENAME).write_text(
        "revocations: []\n", encoding="utf-8"
    )
    return root


def _install_root(tmp_path: Path) -> Path:
    """A repository to install into: the committed tree's data, and no packs yet.

    A pack installs against the repository root the engine is opened at, so a
    pack a third party publishes has to be installed into a repository that
    *holds* it. Copying the catalog, the schemas and the packs is what makes the
    temporary root a real one: the engine reads the catalog for its vocabulary
    and the schemas for its manifest artefacts, and a root missing either would
    fail for a reason that is not the registry's.
    """
    root = tmp_path / "install"
    for name in ("catalog", "schemas", "packs"):
        shutil.copytree(ROOT / name, root / name)
    return root


def _staged(
    install_root: Path,
    directory: str,
    *,
    name: str,
    version: str,
    services: tuple[str, ...],
) -> Path:
    """Write a pack under `install_root` and export it to the repo-relative form.

    The pack is built with an absolute `provides` path -- the form a pack
    developed outside its repository carries -- and then exported, which is the
    publishing button's first act. What lands on disk is the manifest a publisher
    commits: paths that resolve against the repository root, not against the
    machine the pack was developed on.
    """
    manifest = pack(
        install_root / "packs" / "community",
        directory,
        version=version,
        services=services,
        edits=(("name: ", f"name: {name}"),),
    )
    template = export_template(manifest, root=install_root)
    manifest.write_text(
        yaml.safe_dump(template, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )
    return manifest


def _publish(
    registry: Path,
    install_root: Path,
    directory: str,
    *,
    name: str,
    version: str,
    services: tuple[str, ...],
) -> Pointer:
    """Stage and publish one version, returning the pointer that pins it."""
    manifest = _staged(
        install_root, directory, name=name, version=version, services=services
    )
    publication = publish(
        registry,
        manifest,
        repo=install_root.as_posix(),
        commit=COMMIT,
        tier="community",
    )
    return publication.pointer


def _entry_of(registry: Path, name: str, version: str) -> Pointer:
    """The pointer the committed index carries for `name` at `version`."""
    entry = load_index(registry).find(name, version)
    assert entry is not None, f"{name} {version} is not in the index"
    return entry.pointer


# -- the four tiers ---------------------------------------------------------


def test_the_four_tiers_are_exactly_the_ones_the_policy_closes() -> None:
    """A tree that dropped or added a tier would make a pointer unjudgeable."""
    tiers = load_tiers(COMMITTED)
    assert tuple(tiers) == TIER_NAMES


def test_only_the_local_tier_stays_out_of_the_index() -> None:
    """A sideloaded pack is not published, and every other tier is."""
    tiers = load_tiers(COMMITTED)
    published = {name for name, tier in tiers.items() if tier.publishes}
    assert published == {"official", "verified", "community"}
    assert tiers["local"].install_flow == "config"
    assert tiers["local"].banner is not None


def test_an_unreviewed_tier_may_not_permit_a_dangerous_permission() -> None:
    """A community pack is accepted without review, so it carries no danger."""
    tiers = load_tiers(COMMITTED)
    assert not tiers["community"].permits_flagged
    assert tiers["official"].permits_flagged
    assert tiers["verified"].permits_flagged


def test_a_tier_list_missing_one_tier_is_refused(tmp_path: Path) -> None:
    """Dropping `local` would leave every `local` pointer unjudgeable."""
    registry = _registry(tmp_path)
    document = yaml.safe_load(
        (registry / layout.TIERS_FILENAME).read_text(encoding="utf-8")
    )
    document["tiers"] = [row for row in document["tiers"] if row["name"] != "local"]
    (registry / layout.TIERS_FILENAME).write_text(
        yaml.safe_dump(document, sort_keys=False), encoding="utf-8"
    )
    with pytest.raises(TierError):
        load_tiers(registry)


# -- the generator and the committed tree -----------------------------------


def test_the_committed_index_is_what_a_fresh_generation_writes() -> None:
    """CI's freshness check, run against the tree as committed."""
    assert verify_current(COMMITTED) == ()


def test_a_stale_committed_file_is_reported(tmp_path: Path) -> None:
    """A forgotten regeneration is a red build, not a store that cannot see a pack."""
    registry = _registry(tmp_path)
    install_root = _install_root(tmp_path)
    _publish(
        registry,
        install_root,
        "solar_shade",
        name="solar_shade",
        version="1.0.0",
        services=("light.turn_on",),
    )
    generate(registry)
    assert verify_current(registry) == ()
    index_path = registry / layout.INDEX_FILENAME
    index_path.write_text(
        index_path.read_text(encoding="utf-8") + "\n", encoding="utf-8"
    )
    assert verify_current(registry) != ()


def test_a_local_pointer_is_published_nowhere(tmp_path: Path) -> None:
    """A `local` pointer may sit in the tree without ever being offered."""
    registry = _registry(tmp_path)
    destination = (
        registry / layout.POINTERS_DIRECTORY / "local" / "garage_door" / "1.0.0.yaml"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        yaml.safe_dump(
            {
                "name": "garage_door",
                "version": "1.0.0",
                "repo": ".",
                "commit": COMMIT,
                "path": "packs/official/garage.yaml",
                "sha256": "sha256:" + "0" * 64,
                "tier": "local",
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    generate(registry)
    assert load_index(registry).names() == ()


# -- the publishing checks --------------------------------------------------


def test_a_malformed_pointer_fails_the_schema_check(tmp_path: Path) -> None:
    """The one failure that makes every later question moot is named here."""
    registry = _registry(tmp_path)
    findings = check_schema(
        {"name": "half_a_pointer", "version": "1.0.0", "tier": "community"}, registry
    )
    assert findings
    messages = " ".join(finding.message for finding in findings)
    assert "repo" in messages or "required" in messages


def test_the_schema_refuses_a_commit_that_is_not_a_revision(tmp_path: Path) -> None:
    """A pointer is a pin, so its `commit` and `sha256` are checked for shape."""
    registry = _registry(tmp_path)
    schema = pointer_schema(registry)
    document = {
        "name": "x",
        "version": "1.0.0",
        "repo": ".",
        "commit": "not-a-sha",
        "path": "packs/x.yaml",
        "sha256": "sha256:" + "z" * 64,
        "tier": "community",
    }
    assert schema_errors(document, schema)


@pytest.mark.parametrize(
    ("name", "existing"),
    [
        ("motion_light", "motion-light"),
        ("motion-ligh", "motion-light"),
        ("m0ti0n-light", "motion-light"),
    ],
)
def test_a_confusable_name_is_a_typosquat(name: str, existing: str) -> None:
    """Each of the three ways a name borrows another's is caught."""
    assert check_typosquat(name, [existing])


def test_an_unrelated_name_is_not_a_typosquat() -> None:
    """The check does not fire on every name, only on a confusable one."""
    assert check_typosquat("garage_door", ["motion-light", "house"]) == ()


def test_a_dangerous_service_is_refused_by_an_unreviewed_tier(tmp_path: Path) -> None:
    """A community pack may not carry a flagged service; the lint says so."""
    registry = _registry(tmp_path)
    install_root = _install_root(tmp_path)
    manifest = _staged(
        install_root,
        "unlock_on_arrival",
        name="unlock_on_arrival",
        version="1.0.0",
        services=("lock.unlock",),
    )
    pointer = Pointer(
        name="unlock_on_arrival",
        version="1.0.0",
        repo=install_root.as_posix(),
        commit=COMMIT,
        path="packs/community/unlock_on_arrival/manifest.yaml",
        sha256=pack_digest(packs.load_manifest(manifest)),
        tier="community",
    )
    report = run_checks(
        Submission(pointer=pointer, manifest=manifest, root=install_root),
        registry_root=registry,
    )
    assert not report.ok
    assert any(finding.check == "permissions" for finding in report.findings)


def test_a_revoked_pack_fails_its_check() -> None:
    """The revocation list is read beside the pointer, not after install."""
    entry = Pointer(
        name="withdrawn",
        version="1.0.0",
        repo=".",
        commit=COMMIT,
        path="packs/official/withdrawn.yaml",
        sha256="sha256:" + "0" * 64,
        tier="official",
    )
    revocation = Revocation(name="withdrawn", reason="a defect in every release")
    findings = check_revocation(entry, (revocation,))
    assert findings
    assert "a defect in every release" in findings[0].message


# -- publish, generate, install, run ----------------------------------------


def test_a_third_party_publishes_and_installs_a_pack_end_to_end(
    tmp_path: Path, vocabulary: Vocabulary
) -> None:
    """The phase's exit criterion, driven from export to a scenario run."""
    registry = _registry(tmp_path)
    install_root = _install_root(tmp_path)
    pointer = _publish(
        registry,
        install_root,
        "hallway_motion",
        name="hallway_motion",
        version="1.0.0",
        services=("light.turn_on",),
    )
    generate(registry)

    # The pointer pins the digest of exactly what the store reads back, and the
    # pinned manifest names its file the way the sandbox installs it.
    assert pointer == _entry_of(registry, "hallway_motion", "1.0.0")
    manifest = install_root / pointer.path
    assert pointer.sha256 == pack_digest(packs.load_manifest(manifest))

    # The checks a publishing pull request runs pass, with nothing to fix.
    report = run_checks(
        Submission(pointer=pointer, manifest=manifest, root=install_root),
        existing_names=load_index(registry).names(),
        registry_root=registry,
    )
    assert report.ok, [finding.message for finding in report.findings]

    # A store over the committed index installs it, and the engine records it.
    store = Store.open(registry)
    session = open_session(house="minimal", vocabulary=vocabulary, root=install_root)
    result = store.install(session, "hallway_motion")
    assert result["installed"] is True
    assert result["tier"] == "community"
    assert result["pinned"] == pointer.sha256
    installed = session.snapshot()["engine_state"]["installed_packs"]
    assert installed["hallway_motion"]["version"] == "1.0.0"

    # And a committed scenario still runs on the fake house with the pack present.
    scenario = _load(SCENARIOS / "01-exterior-lights-after-restart.yaml")
    scenario_session = _scenario_session(scenario, vocabulary, install_root)
    store.install(scenario_session, "hallway_motion")
    run = _run(scenario, scenario_session)
    assert run.name == scenario.name


def test_an_install_refuses_a_manifest_the_pointer_does_not_pin(
    tmp_path: Path, vocabulary: Vocabulary
) -> None:
    """A pointer is a pin: a manifest edited after publishing is refused."""
    registry = _registry(tmp_path)
    install_root = _install_root(tmp_path)
    pointer = _publish(
        registry,
        install_root,
        "hallway_motion",
        name="hallway_motion",
        version="1.0.0",
        services=("light.turn_on",),
    )
    generate(registry)

    # An edit the publisher did not sign changes the canonical document's digest.
    manifest = install_root / pointer.path
    manifest.write_text(
        manifest.read_text(encoding="utf-8").replace(
            "a pack for the test", "a pack for the test, edited"
        ),
        encoding="utf-8",
    )

    store = Store.open(registry)
    session = open_session(house="minimal", vocabulary=vocabulary, root=install_root)
    with pytest.raises(RegistryError):
        store.install(session, "hallway_motion")


def test_a_revoked_pack_is_refused_by_the_store(
    tmp_path: Path, vocabulary: Vocabulary
) -> None:
    """Withdrawing a pack withdraws it from installs, not only from review."""
    registry = _registry(tmp_path)
    install_root = _install_root(tmp_path)
    _publish(
        registry,
        install_root,
        "hallway_motion",
        name="hallway_motion",
        version="1.0.0",
        services=("light.turn_on",),
    )
    _publish(
        registry,
        install_root,
        "quiet_hours",
        name="quiet_hours",
        version="1.0.0",
        services=("light.turn_off",),
    )
    (registry / layout.REVOCATIONS_FILENAME).write_text(
        yaml.safe_dump(
            {
                "revocations": [
                    {"name": "hallway_motion", "reason": "publishes an unwanted light"}
                ]
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    generate(registry)
    assert load_revocations(registry)

    store = Store.open(registry)
    session = open_session(house="minimal", vocabulary=vocabulary, root=install_root)
    with pytest.raises(RegistryError):
        store.install(session, "hallway_motion")
    # The other pack is untouched by the revocation beside it.
    assert store.install(session, "quiet_hours")["installed"] is True


# -- the update gate --------------------------------------------------------


def test_an_update_that_widens_a_grant_is_gated(
    tmp_path: Path, vocabulary: Vocabulary
) -> None:
    """A new version that adds a permission needs the change accepted."""
    registry = _registry(tmp_path)
    install_root = _install_root(tmp_path)
    _publish(
        registry,
        install_root,
        "hallway_motion",
        name="hallway_motion",
        version="1.0.0",
        services=("light.turn_on",),
    )
    # The next version lives beside the first, because two versions of one pack
    # cannot share a path and the diff needs both on disk at once.
    _publish(
        registry,
        install_root,
        "hallway_motion_next",
        name="hallway_motion",
        version="1.1.0",
        services=("light.turn_on", "light.turn_off"),
    )
    generate(registry)

    # The publishing check reports the gain, naming the service.
    previous = install_root / _entry_of(registry, "hallway_motion", "1.0.0").path
    pointer = _entry_of(registry, "hallway_motion", "1.1.0")
    findings = check_permission_diff(
        Submission(
            pointer=pointer,
            manifest=install_root / pointer.path,
            root=install_root,
            previous=previous,
        ),
        load_tiers(registry),
    )
    assert any("light.turn_off" in finding.message for finding in findings)

    # The store refuses the update until the change is accepted.
    store = Store.open(registry)
    session = open_session(house="minimal", vocabulary=vocabulary, root=install_root)
    store.install(session, "hallway_motion", version="1.0.0")
    with pytest.raises(RegistryError):
        store.update(session, "hallway_motion")

    accepted = store.update(session, "hallway_motion", accept_permission_changes=True)
    assert accepted["updated"] is True
    assert "light.turn_off" in accepted["gained"]
    installed = session.snapshot()["engine_state"]["installed_packs"]
    assert installed["hallway_motion"]["version"] == "1.1.0"


def test_a_version_that_adds_nothing_installs_without_a_gate(
    tmp_path: Path, vocabulary: Vocabulary
) -> None:
    """A patch release that changes nothing about permissions is not gated."""
    registry = _registry(tmp_path)
    install_root = _install_root(tmp_path)
    _publish(
        registry,
        install_root,
        "hallway_motion",
        name="hallway_motion",
        version="1.0.0",
        services=("light.turn_on",),
    )
    _publish(
        registry,
        install_root,
        "hallway_motion_next",
        name="hallway_motion",
        version="1.0.1",
        services=("light.turn_on",),
    )
    generate(registry)

    store = Store.open(registry)
    session = open_session(house="minimal", vocabulary=vocabulary, root=install_root)
    store.install(session, "hallway_motion", version="1.0.0")
    result = store.update(session, "hallway_motion")
    assert result["updated"] is True
    assert result["gained"] == ()


# -- the committed registry itself ------------------------------------------


def test_every_pointer_in_the_committed_tree_loads() -> None:
    """The seeded official pointers are readable and name a known tier."""
    tiers = load_tiers(COMMITTED)
    files = pointer_files(COMMITTED)
    assert files
    for path in files:
        pointer = load_pointer(path)
        assert pointer.tier in tiers


# -- helpers ----------------------------------------------------------------


def _load(path: Path) -> Scenario:
    """`load_scenario`, imported lazily so an import error stays local."""
    from sim.scenario import load_scenario

    return load_scenario(path)


def _run(scenario: Scenario, session: OpenHouse) -> RunResult:
    """`run_scenario`, imported lazily for the same reason as `_load`."""
    from sim.scenario import run_scenario

    return run_scenario(scenario, session)


def _scenario_session(
    scenario: Scenario, vocabulary: Vocabulary, root: Path
) -> OpenHouse:
    """A session from the scenario's `given`, opened at `root`.

    `openhouse.scenarios.open_scenario` is the same open, except it always opens
    at the project root; a scenario whose session installs a pack needs the
    repository the pack was published into, so the `given` block is bound here.
    """
    given = scenario.given
    return open_session(
        house=given.house,
        vocabulary=vocabulary,
        seed=given.seed,
        started_at=given.started_at,
        root=root,
        house_settings=given.enable_flags,
    )
