"""The MCP face: the same ten operations, and the scenario runner's entry point.

`control-surface` requires this server to be a *thin adapter over the same
registry*: one tool per registry operation, each named by the operation's `name`
with its input schema derived from that operation's registry descriptor, plus the
scenario runner's entry point as `run_scenario`. The reason is the exit
criterion's -- this is the face an AI agent drives, so a tool that behaved
differently from the library call the scenario runner makes would be a tool whose
scenarios test a different system.

Which is why nothing here is declared twice. The tool set *is* `OPERATIONS`, the
schema *is* `input_schema(operation)` -- the same object the CLI's arguments are
declared from, so "the CLI's arguments and the tool's inputs are one schema seen
twice" is an equality a check can assert rather than a resemblance a reader has
to judge -- and the call is `operation.handler(session, **arguments)`, the one
line every face forwards with. The single thing outside the registry is
`run_scenario`, which the requirement names as a **client entry point** composed
over the ten operations and which a check must therefore set aside rather than
compare as an operation.

**Why the low-level `Server` and not `MCPServer`.** `MCPServer.add_tool` derives
a tool's schema from the function's signature through pydantic, which would make
a tool's inputs a second derivation that no longer equals what `input_schema`
returns: pydantic adds its own titles, spells an optional parameter as an
`anyOf` with a null branch, and drops the descriptor's `additionalProperties:
false`. Registering the tools directly lets the advertised schema *be* the
registry's, which is the difference between a property and a hope.

The server holds one session, as the CLI holds one, because a surface is a face
of a session and not a session factory. `run_scenario` is the exception the
requirement makes: a scenario's `given` block names its own house, so that tool
opens its own session from the block, exactly as `scenario run` does.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

from jsonschema.protocols import Validator
from jsonschema.validators import Draft202012Validator
from mcp.server import Server, ServerRequestContext
from mcp.types import (
    CallToolRequestParams,
    CallToolResult,
    ListToolsResult,
    PaginatedRequestParams,
    TextContent,
    Tool,
)

from sim.scenario import ScenarioFailed, load_scenario
from sim.scenario.runner import run_scenario

from .operations import OPERATIONS, Operation, Parameter, input_schema
from .results import result_document
from .scenarios import open_scenario, run_corpus

if TYPE_CHECKING:
    from collections.abc import Mapping

    from .facade import OpenHouse

__all__ = ["SCENARIO_ENTRY", "SERVER_NAME", "build_server"]

#: The name the server is exposed under, which `control-surface` fixes.
SERVER_NAME = "openhouse"


def _run_scenario(session: OpenHouse, *, path: str, seed: int | None = None) -> object:
    """Run the scenario at `path`, or every scenario in it, on its own session.

    `session` is read for one thing only -- the vocabulary its house was built
    with -- because a scenario's `given` block names its own house: the run is
    opened from the block and not from the server's session, which is the
    distinction `scenario-runner` draws between the runner and the thing that
    opens a session for it.

    A directory is a corpus, as it is on the CLI, because the corpus is a set of
    seeds and running one file at a time would be a reading list.
    """
    vocabulary = session.house.vocabulary
    if Path(path).is_dir():
        return run_corpus(path, vocabulary=vocabulary, seed=seed)
    scenario = load_scenario(path)
    return run_scenario(
        scenario, open_scenario(scenario, vocabulary=vocabulary, seed=seed)
    )


#: The scenario runner's entry point, declared as an `Operation` so the tool is
#: generated by the same code path as the ten. It is deliberately **not** in
#: `OPERATIONS`: `control-surface` calls it a client entry point composed over
#: the operations, and the registry comparison sets it aside by name.
SCENARIO_ENTRY = Operation(
    name="run_scenario",
    summary="Run a scenario, or a corpus of them, and report what happened.",
    scope=(
        "Phase 1: the runner's own entry point. The house, the seed and the "
        "clock start come from each scenario's `given` block, and the run uses "
        "the server's session for its vocabulary only."
    ),
    parameters=(
        Parameter(
            "path",
            "string",
            "A scenario file, or a directory of them to run as a corpus.",
        ),
        Parameter(
            "seed",
            "integer",
            "The seed to run at, overriding the given block's.",
            required=False,
            default=None,
        ),
    ),
    handler=_run_scenario,
)


def build_server(session: OpenHouse) -> Server:
    """The `openhouse` server over `session`: the ten operations and `run_scenario`.

    Drivable by an in-process client -- `mcp.Client(server)` in a test -- so the
    surface can be proven without a transport process, which is what the
    requirement asks for. Nothing here decides anything: a tool call is validated
    against the schema the tool itself advertises and then forwarded, and a result
    is the document the CLI writes.
    """

    async def list_tools(
        context: ServerRequestContext, params: PaginatedRequestParams | None
    ) -> ListToolsResult:
        return ListToolsResult(
            tools=[
                _tool(operation) for operation in (*OPERATIONS.values(), SCENARIO_ENTRY)
            ]
        )

    async def call_tool(
        context: ServerRequestContext, params: CallToolRequestParams
    ) -> CallToolResult:
        arguments = dict(params.arguments or {})
        operation = _operation(params.name)
        if operation is None:
            return _refused(params.name, f"no tool is named {params.name!r}")
        refusal = _refuse_arguments(operation, arguments)
        if refusal is not None:
            return refusal
        try:
            result = operation.handler(session, **arguments)
        except ScenarioFailed as failure:
            return _failed_scenario(failure)
        except Exception as error:
            # Everything else the call raised: the tool is what failed, and the
            # exception's own words are the cause a caller needs.
            return _refused(operation.name, f"{type(error).__name__}: {error}")
        return _document(result_document(operation.name, result))

    return Server(SERVER_NAME, on_list_tools=list_tools, on_call_tool=call_tool)


def _operation(name: str) -> Operation | None:
    """The operation a tool name resolves to, or `None` when nothing is named that.

    `run_scenario` is looked up second so the registry's own names are never
    shadowed by the client entry point, whatever either is called.
    """
    if name == SCENARIO_ENTRY.name:
        return SCENARIO_ENTRY
    return OPERATIONS.get(name)


def _tool(operation: Operation) -> Tool:
    """One operation, as an MCP tool: the registry's name, schema and words.

    The description is the descriptor's `summary` and `scope` together, which is
    the text the CLI's `--help` prints, so an agent reading a tool's description
    meets the operation's boundary -- including the three whose `scope` names a
    later phase -- rather than only its name.
    """
    return Tool(
        name=operation.name,
        description=f"{operation.summary}\n\n{operation.scope}",
        input_schema=input_schema(operation),
    )


def _refuse_arguments(
    operation: Operation, arguments: Mapping[str, object]
) -> CallToolResult | None:
    """The refusal for arguments the tool's own schema does not accept, or `None`.

    The schema checked here is the object the tool advertises, so a caller that
    read the tool's inputs and a call that was refused cannot disagree about what
    was allowed. Refusing is the MCP face's half of what Typer does for the CLI
    -- a call that is not the operation's is a bad call rather than an operation
    that failed -- and it decides nothing about the call itself, which is what
    keeps this a thin adapter.
    """
    validator = cast("Validator", Draft202012Validator(input_schema(operation)))
    error = next(iter(validator.iter_errors(cast("Any", dict(arguments)))), None)
    if error is None:
        return None
    location = "/".join(str(part) for part in error.absolute_path) or "the call"
    return _refused(operation.name, f"{location}: {error.message}")


def _document(document: object) -> CallToolResult:
    """A result, as the one JSON object every surface reports.

    Text rather than structured content: the document *is* the result, and a
    second, typed rendering beside it would be a second answer to what the
    operation returned. It is byte-identical to what the CLI prints.
    """
    return _text(json.dumps(document, sort_keys=True), is_error=False)


def _failed_scenario(failure: ScenarioFailed) -> CallToolResult:
    """A scenario that did not pass, as the CLI reports it: the summary, then the report.

    Two blocks because the CLI writes two things -- the one-line summary on
    stderr and the report document on stdout -- and an agent that reads the first
    can stop there while a caller that needs the decision the scenario disagreed
    with, and the log slice up to it, has them.
    """
    return CallToolResult(
        content=[
            TextContent(type="text", text=failure.report.summary()),
            TextContent(
                type="text",
                text=json.dumps(failure.report.to_document(), sort_keys=True),
            ),
        ],
        is_error=True,
    )


def _refused(name: str, reason: str) -> CallToolResult:
    """A call the server will not make, as a failed result naming the tool.

    A result rather than a raised exception, because a client reads a failed tool
    call as data it can act on: an exception out of the handler would reach the
    client as a transport-level error saying nothing about which tool was wrong.
    """
    return _text(f"Error: {name}: {reason}", is_error=True)


def _text(text: str, *, is_error: bool) -> CallToolResult:
    """One block of text as a tool result."""
    return CallToolResult(
        content=[TextContent(type="text", text=text)], is_error=is_error
    )
