"""The generated panel types must match the schemas they came from.

`schemas/` is the single source of truth for the engine, the panel, the pack CI
and the AI tools, and the panel is the one consumer that cannot import a Python
model. Its copy of every frozen document is generated by
`panel/scripts/generate-types.mjs` -- so the thing worth testing is not that the
generator ran once, but that the *committed* file is what the generator produces
now. A schema that moves without the panel being regenerated is a panel that
validates against the wrong contract, and it is the failure this check exists to
catch.

The check runs the real generator through Node rather than reimplementing it in
Python. A Python reimplementation would be a second generator, free to disagree
with the one that actually writes the file, and the test would then be checking
itself. It is skipped, loudly, when Node is absent: a machine with no Node can
still run the repository's other checks, and a skip is the honest report of "this
was not verified here".
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest

PANEL = "panel"
GENERATED = "src/types/generated.ts"
GENERATOR = "scripts/generate-types.mjs"
VERSION = re.compile(r"^\d+\.\d+\.\d+$")

node = shutil.which("node")
requires_node = pytest.mark.skipif(
    node is None,
    reason="node is not installed; the type generator cannot be run",
)


def repo_root() -> Path:
    """The repository root, derived from this file's position.

    `panel/tests/<this file>` is three levels down. Derived rather than read from
    an environment variable, so the check works the same in CI and on a laptop.
    """
    return Path(__file__).resolve().parents[2]


def concept_key(path: Path, schemas: Path) -> str:
    """The `SCHEMA_VERSIONS` key a schema file contributes, as the generator makes it.

    A version file is `<concept>/<semver>.json` and keys by its directory, so a
    concept does not change key every release; everything else keys by its own
    path under `schemas/` with the extension dropped.
    """
    relative = path.relative_to(schemas)
    if VERSION.match(relative.stem) and relative.parent != schemas:
        return relative.parent.as_posix()
    return relative.with_suffix("").as_posix()


def run_generator(*args: str) -> subprocess.CompletedProcess[str]:
    """Run the generator from the panel directory and capture its output."""
    panel = repo_root() / PANEL
    assert node is not None
    # `encoding` is pinned rather than left to the platform: the schemas carry
    # em dashes and section marks in their descriptions, and on Windows the
    # default codec would decode Node's UTF-8 output as cp1252 -- making the
    # comparison fail on characters that are identical in both files.
    return subprocess.run(
        [node, GENERATOR, *args],
        cwd=panel,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )


@requires_node
def test_the_committed_types_are_what_the_generator_produces() -> None:
    """Regenerate in memory and compare against the committed file.

    Any difference is a failure, including whitespace: the file is checked in, so
    a reformat that does not change the types would still show as a diff on every
    developer's machine and would train them to ignore the file.
    """
    generated = repo_root() / PANEL / GENERATED
    assert generated.is_file(), f"{GENERATED} is missing; run `npm run gen:types`"

    result = run_generator("--stdout")
    assert result.returncode == 0, result.stderr
    assert result.stdout == generated.read_text(encoding="utf-8"), (
        "panel/src/types/generated.ts is stale: run `npm run gen:types` in panel/"
    )


@requires_node
def test_every_current_schema_concept_has_a_type() -> None:
    """Each concept's current version is represented in the generated file.

    The generator picks the version no other version supersedes; this asserts it
    picked one for every concept, so a schema added under a new directory cannot
    be silently absent from the panel's types.
    """
    root = repo_root()
    schemas = root / "schemas"
    generated = (root / PANEL / GENERATED).read_text(encoding="utf-8")

    concepts: set[str] = set()
    for path in sorted(schemas.rglob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(document.get("schema_version"), str):
            continue
        concepts.add(concept_key(path, schemas))

    assert concepts, "no schemas found; the test is looking in the wrong place"
    for concept in sorted(concepts):
        assert f'"{concept}"' in generated, (
            f"concept {concept!r} has no entry in {GENERATED}"
        )


@requires_node
def test_generated_types_are_marked_generated() -> None:
    """The file says it is generated, so nobody edits it by hand.

    A hand edit to a generated file is invisible until the next regeneration
    silently reverts it. The header is the only warning a reader gets, so it is
    asserted rather than assumed.
    """
    root = repo_root()
    header = (root / PANEL / GENERATED).read_text(encoding="utf-8").splitlines()
    assert header, f"{GENERATED} is empty"
    first = header[0]
    assert "Generated by" in first and "generate-types.mjs" in first, first
    assert "do not edit by hand" in first, first


@requires_node
def test_the_key_documents_are_typed() -> None:
    """The interfaces the panel actually names exist, by name.

    This is the cheapest guard against a generator change that renames or drops
    the handful of types the panel imports. It asserts the names, not their
    contents -- the drift check above owns the contents.
    """
    generated = (repo_root() / PANEL / GENERATED).read_text(encoding="utf-8")
    for name in (
        "export interface House",
        "export interface HouseRoom",
        "export interface HouseBinding",
        "export interface PackManifest",
        "export interface ExportDocument",
        "export interface Profile",
        "export interface RoomType",
        "export interface Slot",
        "export interface Mode",
        "export const SCHEMA_VERSIONS",
    ):
        assert name in generated, f"{name!r} is missing from {GENERATED}"
